config/routes.rb
DeviseBase::Application.routes.draw do

  devise_for :admins

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root :to => 'statics#home'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :timeoutable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  def self.find_for_facebook_oauth(access_token, signed_in_resource=nil)
    data = access_token.extra.raw_info
    if user = User.where(:email => data.email).first
      user
    else # Create a user with a stub password.
      User.create!(:email => data.email, :password => Devise.friendly_token[0,20])
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController

  def home
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/views/layouts/_alert.html.haml
= alert

app/views/layouts/_notice.html.haml
= notice

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    %title OmniauthDemo
    = stylesheet_link_tag "application", :media => 'all'
    = javascript_include_tag "application"
    = csrf_meta_tags
    -#%link{:href => image_path('favicon.ico'), :type => 'image/x-icon', :rel => 'icon'}
  %body
    = render 'layouts/notice', :notice => notice
    = render 'layouts/alert', :alert => alert
    = yield

app/views/statics/home.html.haml
%h1 Root Page
- if signed_in?
  %p
    You are signed in as
  %ul
  - if user_signed_in?
    %li
      a user:
      = current_user.email
      = link_to 'sign out', destroy_user_session_path, :method => :delete
  - if admin_signed_in?
    %li
      an admin:
      = current_admin.email
      = link_to 'sign out', destroy_admin_session_path, :method => :delete
  %hr
%p
  Please sign in as:
  = link_to 'user', new_user_session_path unless user_signed_in?
  = link_to 'admin', new_admin_session_path unless admin_signed_in?
%ul
  %li= link_to 'Google', '/auth/google_oauth2'
  %li= link_to 'Twitter', '/auth/twitter'
  %li= link_to 'Github', '/auth/github'
%hr

%h1 Readme

%p The Gemfile contains both thin and foreman, and it is recommended you use thin as your client and foreman to manage it.
%p Start the server with 'foreman start'.

%p This page is located in app/views/pages/home.html.erb. Please modify it to reflect your home page.
%p This base comes with the following, all in vendor/assets:

%h4 CSS
%ul
  %li Blueprint
  %ul
    %li ie.css
    %li typography.css
    %li reset.css
  %li 1140 CSS Grid
  %ul
    %li 1140.css
    %li styles.css.scss
  %li formalize.css.scss
%hr
%h4 JS
%ul
  %li 1140 CSS Grid
  %ul
    %li css3-mediaqueries.js
  %li jquery.formalize.min.js
  %li jquery.url.js
%hr
%h4 Images
%ul
  %li Mostly complete icon set.
%hr
%p The app/assets/stylesheets/application.css loads vendor sheets, plus the default.css.scss file, into which all SASS sheets should be @imported. All SASS sheets to be imported need to begin with an underscore.
%p The app/assets/javascripts/application.js loads all .js files, as well as the jquery-ui plugin, served from rails.

%h2 Setup

%ul
  %li Set both your development and production API keys and secrets in /config/initializers/dev_environment.rb
  %li Add yourself as an admin using the console [ User.create!(:email => 'YOUR_EMAIL', :password => 'YOUR_PASSWORD') ]
  %li Start the server! [ foreman start ] It'll be available at localhost:5000

%h2 Deploying on Heroku (assumes an existing git repository)

%code
  gem install heroku
  heroku keys:add
  heroku create --stack cedar
  git checkout -b heroku
  git push heroku heroku:master
  heroku run rake db:migrate